from .match_views import (
    BaseMatchListView,
    UpcomingMatchListView,
    PreviousMatchListView,
    InProgressMatchListView,
    PostponedMatchListView,
    CancelledMatchListView,
    AllMatchListView,
    MatchDetailView,
    MatchCreateView,
    MatchUpdateView,
    MatchDeleteView,
    MatchImportView,
    MatchImportCSVTemplateView,
    MatchProcessCSVView,
    MatchBulkDataImportView,
    MatchBulkDataExportView,
    MatchBulkDataProcessCSVView,
)
from .match_note_views import (
    MatchNoteListView,
    MatchNoteDetailView,
    MatchNoteCreateView,
    MatchNoteUpdateView,
    MatchNoteDeleteView,
    delete_match_note_ajax
)
from .match_player_stats_views import (
    MatchPlayerStatsListView,
    MatchPlayerStatsDetailView,
    MatchPlayerStatsCreateView,
    MatchPlayerStatsUpdateView,
    MatchPlayerStatsDeleteView,
    MatchPlayerStatsManageView,
    MatchPlayerStatsSummaryView,
    PlayerStatsHistoryView,
    MatchPlayerStatsQuickAddView,
)

__all__ = [
    # Match views
    'UpcomingMatchListView',
    'PreviousMatchListView',
    'InProgressMatchListView',
    'PostponedMatchListView',
    'CancelledMatchListView',
    'AllMatchListView',
    'MatchDetailView',
    'MatchCreateView',
    'MatchUpdateView',
    'MatchDeleteView',
    'MatchImportView',
    'MatchImportCSVTemplateView',
    'MatchProcessCSVView',
    'MatchBulkDataImportView',
    'MatchBulkDataExportView',
    'MatchBulkDataProcessCSVView',
    # Match note views
    'MatchNoteListView',
    'MatchNoteDetailView',
    'MatchNoteCreateView',
    'MatchNoteUpdateView',
    'MatchNoteDeleteView',
    'delete_match_note_ajax',
    # Player stats views
    'MatchPlayerStatsListView',
    'MatchPlayerStatsDetailView',
    'MatchPlayerStatsCreateView',
    'MatchPlayerStatsUpdateView',
    'MatchPlayerStatsDeleteView',
    'MatchPlayerStatsManageView',
    'MatchPlayerStatsSummaryView',
    'PlayerStatsHistoryView',
    'MatchPlayerStatsQuickAddView',
]
