# Generated by Django 5.2 on 2025-05-15 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-created'], 'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='address',
        ),
        migrations.RemoveField(
            model_name='player',
            name='city',
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='identity_document',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='player',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sport_name',
        ),
        migrations.AddField(
            model_name='player',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/photos/', verbose_name='Foto'),
        ),
    ]
