# Generated by Django 5.2 on 2025-05-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_options_remove_player_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='player',
            name='identity_document',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento de identidad'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='player',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='player',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='player',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comunidad Autónoma'),
        ),
        migrations.AddField(
            model_name='player',
            name='sport_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre deportivo'),
        ),
    ]
