# Generated by Django 5.2 on 2025-06-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dorsal',
            field=models.PositiveIntegerField(blank=True, help_text='Número de dorsal del jugador', null=True, verbose_name='Dorsal'),
        ),
    ]
