# Generated by Django 5.2 on 2025-06-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('season', '0002_alter_season_is_active'),
        ('team', '0003_rename_ciudad_team_city_rename_entrenador_team_coach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('away_team', models.CharField(help_text='Nombre del equipo rival', max_length=200, verbose_name='Equipo visitante')),
                ('match_date', models.DateTimeField(help_text='Fecha y hora programada para el partido', verbose_name='Fecha y hora del partido')),
                ('venue', models.CharField(blank=True, help_text='Nombre del estadio o campo donde se juega', max_length=200, null=True, verbose_name='Estadio/Campo')),
                ('match_type', models.CharField(choices=[('friendly', 'Amistoso'), ('league', 'Liga'), ('cup', 'Copa'), ('playoff', 'Playoff'), ('training', 'Entrenamiento')], default='friendly', max_length=20, verbose_name='Tipo de partido')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En curso'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado'), ('postponed', 'Aplazado')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('home_score', models.PositiveIntegerField(blank=True, help_text='Goles marcados por el equipo local', null=True, verbose_name='Goles equipo local')),
                ('away_score', models.PositiveIntegerField(blank=True, help_text='Goles marcados por el equipo visitante', null=True, verbose_name='Goles equipo visitante')),
                ('notes', models.TextField(blank=True, help_text='Observaciones adicionales sobre el partido', null=True, verbose_name='Notas')),
                ('is_home', models.BooleanField(default=True, help_text='Indica si el partido se juega en casa o fuera', verbose_name='Partido en casa')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='team.team', verbose_name='Equipo local')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='season.season', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-match_date'],
            },
        ),
    ]
