# Generated by Django 5.2 on 2025-06-06 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('title', models.CharField(help_text='Título breve de la nota', max_length=200, verbose_name='Título')),
                ('content', models.TextField(help_text='Contenido detallado de la nota', verbose_name='Contenido')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_notes', to='matches.match', verbose_name='Partido')),
            ],
            options={
                'verbose_name': 'Nota de Partido',
                'verbose_name_plural': 'Notas de Partido',
                'ordering': ['-created'],
            },
        ),
    ]
