# Generated by Django 5.2 on 2025-06-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('name', models.CharField(help_text='Nombre del equipo rival', max_length=140, verbose_name='Nombre del rival')),
                ('coach_name', models.CharField(blank=True, help_text='Nombre del entrenador del equipo rival', max_length=140, null=True, verbose_name='Nombre del entrenador')),
                ('field_name', models.CharField(blank=True, help_text='Nombre del campo de juego del equipo rival', max_length=140, null=True, verbose_name='Nombre del campo')),
                ('city', models.CharField(blank=True, help_text='Ciudad donde se encuentra el equipo rival', max_length=100, null=True, verbose_name='Ciudad')),
                ('coach_phone', models.CharField(blank=True, help_text='Número de teléfono del entrenador', max_length=20, null=True, verbose_name='Teléfono del entrenador')),
                ('coach_email', models.EmailField(blank=True, help_text='Correo electrónico del entrenador', max_length=254, null=True, verbose_name='Email del entrenador')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el equipo rival', null=True, verbose_name='Notas del equipo')),
            ],
            options={
                'verbose_name': 'Rival',
                'verbose_name_plural': 'Rivales',
                'ordering': ['name'],
            },
        ),
    ]
