# Generated by Django 5.2 on 2025-06-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivals', '0001_initial'),
        ('season', '0002_alter_season_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rival',
            name='seasons',
            field=models.ManyToManyField(blank=True, help_text='Temporadas en las que participa este equipo rival', to='season.season', verbose_name='Temporadas'),
        ),
    ]
