# Generated by Django 5.2 on 2025-05-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140, verbose_name='Nombre del equipo')),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='equipos/escudos/', verbose_name='Escudo')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('fecha_fundacion', models.DateField(blank=True, null=True, verbose_name='Fecha de fundación')),
                ('entrenador', models.CharField(blank=True, max_length=140, null=True, verbose_name='Entrenador')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Página web oficial')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipo',
            },
        ),
    ]
