# Generated by Django 5.2 on 2025-05-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipo',
            new_name='Team',
        ),
    ]
