# Generated by Django 5.2 on 2025-05-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_equipo_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='ciudad',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='entrenador',
            new_name='coach',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='pais',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='fecha_fundacion',
            new_name='foundation_date',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='web',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='team',
            name='escudo',
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/logos/', verbose_name='Escudo'),
        ),
    ]
