# Generated by Django 5.2 on 2025-06-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activa'),
        ),
    ]
